FROM golang:1.21-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

FROM golang:1.21-alpine

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

COPY --from=builder /go/pkg/mod /go/pkg/mod
COPY . .

CMD ["go", "test", "-v", "./tests/..."]
