FROM golang:1.21-alpine AS builder

WORKDIR /build

RUN apk add --no-cache git

COPY go.mod ./
RUN go mod download

COPY . .

FROM golang:1.21-alpine

RUN apk add --no-cache git

WORKDIR /app

COPY --from=builder /go/pkg /go/pkg
COPY --from=builder /build /app

CMD ["go", "test", "-v", "-count=1", "./tests/..."]
